<?php
function groceries_menu() {
  $items = array();
  $items['groceries'] = array(
      'title' => 'Grocery List',
      'page callback' => 'grocery_list',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function grocery_list() {
    $groceries = array(
        'eggs' => array(
            'price' => 1.99,
            'quantity' => 12,
        ),
        'bread' => array(
            'price' => 2.99,
            'quantity' => 1,
        ),
        'chocolate' => array(
            'price' => 4.99,
            'quantity' => 3,
        ),
    );
    // var_dump($groceries);
    $list = "";

    foreach($groceries as $key => $grocery) {
        $total = $grocery['price']*$grocery['quantity'];
        // var_dump($total);

        $list .= "<p>$grocery[quantity] $key at $grocery[price]/each = $total</p>";

    }
    return $list;
}
